import { PlanStatus } from './plan-status.enum';

export class Plan {
  constructor(
    public readonly id: string,
    public readonly projectId: string,
    public readonly sheetName: string,
    public readonly version: number,
    public readonly status: PlanStatus,
    public readonly createdAt: Date,
    public readonly updatedAt: Date
  ) {}

  static create(projectId: string, sheetName: string, version: number): Plan {
    // In TDD, we might just return the object.
    // UUID will be generated by the repo in this specific architecture 
    // or we can generate it here if we bring uuid lib. 
    // For now I'll leave ID empty or rely on the repository to hydrate it properly 
    // but typically DDD entities have IDs generated at creation.
    // Given the previous existing entities `User` and `Project` check to see how they do it.
    
    // I will checking `project.entity.ts` to coordinate style.
    // For now, I will assume a standard constructor.
    return new Plan(
      '', // ID assigned by persistence usually in this setup if not using UUID here
      projectId,
      sheetName,
      version,
      PlanStatus.DRAFT,
      new Date(),
      new Date()
    );
  }
}
